language: c
os: linux
jobs:
  - stage: lint
    dist: bionic
    addons:
      snaps:
        - cppcheck
    compiler: gcc
    script:
      - cppcheck --version
      - cppcheck --quiet -i fuzz-test -i old -i utest .

  - stage: build
    install: make cmake
    compiler: gcc
    script:
      - bash build.sh
    after_success:
      - bash <(curl -s https://codecov.io/bash)
